### ISSUE TITLE
All marks disappear when commenting lines

### ISSUE THREAD

**Issue by XO39** [jcs-elpa/line-reminder#4]
When I comment a line or more  in the file, anywhere, all marks/annotations are gone!

**Comment by jcs090218** [comment]
Yes, this is a known bug. Emacs has the feature called narrowing & widening; they use this feature to provide some kind of buffer modification restriction. Commenting/Uncommenting will messes up because they uses this functionalities to speed up the buffer modification. I don't know if I am able resolved this kind of issue, since this package couldn't handle buffer restriction like this.

The other way around this, is that you could either define your own commenting and uncommenting functions, like here [#L231](https://github.com/jcs090218/jcs-emacs-init/blob/969dcf71c2e099bf3f12fed733bab1a039dd2dd3/.emacs.jcs/func/jcs-comment.el#L231) in my configuration and pushes the line that had been modified. Otherwise, I don't really know how to resolved the narrowing & widening issue, but I will keep investigate the issue!

**Comment by XO39** [comment]
OK, thanks. Hope to find a solution soon. This packages is so great, and it's just a shame to be affected by such bug. Maybe you can use the fringe instead? Lot's of modes put their marks on the fringe with no issues.

**Comment by jcs090218** [comment]
Is not about the fringe, is about getting the right the modified line, `narrowing/widening` denied this package getting the accurate result. Hence the marking wouldn't have the right output. :( I think I would have to unwiden/unnarrow the buffer to resolve this such of issue! Anyway, thanks for reporting this bug!

**Comment by XO39** [comment]
I just noticed that this issue does not occur in Rails's `html.erb` files with both `web-mode` and `emmet-mode` enabled.

**Comment by jcs090218** [comment]
Sorry for the late reply!

Hmmm... I'm not sure about this issue. I think somehow in between this package and other packages could change the use result effectively. On my end, it seems like whatever I do comment/uncomment in `.erb` file; it changes the whole region no matter what. This gives me the good hint that maybe I could resolve this by using other technique like add an `advice` to comment and uncomment region.

Anyway, thanks for reporting this issue. I might consider resolving this issue by using other method to get around the modification restriction problem from Emacs.

**Comment by jcs090218** [comment]
Okay, I have found a solution for this. call `line-number-at-pos` with absolute argument to `non-nil` should resolve this such a hassle. Also, I have implemented the logic to comment and uncomment lines. This issue shouldn't appear to the later version anymore.

**Comment by jcs090218** [comment]
I will close this for now, let me know if you encountered any issue since the logic is extremely complex (to me)! Hope this issue is resolved and no other side effect occurs! 😕 😄

**Comment by XO39** [comment]
Great work. Cheers!

I'll post again if I found another issue.
